# Generated by Django 2.1.2 on 2018-11-11 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rlocation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rlocation',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rlocation',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
