# Generated by Django 2.1.2 on 2018-11-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rlocation_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rlocation',
            name='Timestamp',
        ),
        migrations.RemoveField(
            model_name='rlocation',
            name='updated',
        ),
    ]
