# Generated by Django 2.1.2 on 2018-11-16 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20181111_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rlocation',
            name='email',
        ),
        migrations.AddField(
            model_name='rlocation',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rlocation',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
