# Generated by Django 2.1.2 on 2018-12-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20181116_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='rlocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
